version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: risk_postgres_gis
    restart: always
    environment:
      POSTGRES_USER: risk_user
      POSTGRES_PASSWORD: risk_password
      POSTGRES_DB: risk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_gis_data:/var/lib/postgresql/data

volumes:
  postgres_gis_data: